//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoContactSyncMod.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Size DeleteTooManyPropertiesForm_Window_Size {
            get {
                return ((global::System.Drawing.Size)(this["DeleteTooManyPropertiesForm_Window_Size"]));
            }
            set {
                this["DeleteTooManyPropertiesForm_Window_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Point DeleteTooManyPropertiesForm_Window_Location {
            get {
                return ((global::System.Drawing.Point)(this["DeleteTooManyPropertiesForm_Window_Location"]));
            }
            set {
                this["DeleteTooManyPropertiesForm_Window_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Size DeleteDuplicatedPropertiesForm_Window_Size {
            get {
                return ((global::System.Drawing.Size)(this["DeleteDuplicatedPropertiesForm_Window_Size"]));
            }
            set {
                this["DeleteDuplicatedPropertiesForm_Window_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Point DeleteDuplicatedPropertiesForm_Window_Location {
            get {
                return ((global::System.Drawing.Point)(this["DeleteDuplicatedPropertiesForm_Window_Location"]));
            }
            set {
                this["DeleteDuplicatedPropertiesForm_Window_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Size DeleteTooBigPropertiesForm_Window_Size {
            get {
                return ((global::System.Drawing.Size)(this["DeleteTooBigPropertiesForm_Window_Size"]));
            }
            set {
                this["DeleteTooBigPropertiesForm_Window_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Point DeleteTooBigPropertiesForm_Window_Location {
            get {
                return ((global::System.Drawing.Point)(this["DeleteTooBigPropertiesForm_Window_Location"]));
            }
            set {
                this["DeleteTooBigPropertiesForm_Window_Location"] = value;
            }
        }
    }
}
